# Site settings
author: Alan Tang
title: ALAN TANG
header-img: img/home-bg.png
email: giabao_tang@yahoo.com
copyright_name: Alan Tang
description: > # this means to ignore newlines until "baseurl:"
  A Soon-to-be Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alantang1369

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
